# Generated by Django 3.0.4 on 2020-03-17 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeId', models.CharField(max_length=10, unique=True)),
                ('EmployeeName', models.CharField(default=None, max_length=15)),
                ('FathersName', models.CharField(default=None, max_length=15)),
                ('MothersName', models.CharField(default=None, max_length=15)),
                ('BloodGroup', models.CharField(default=None, max_length=3)),
                ('DateOfBirth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=6)),
                ('MaritalStatus', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], default=None, max_length=10)),
                ('SpouseName', models.CharField(default=None, max_length=15)),
                ('Designation', models.CharField(default=None, max_length=25)),
                ('EmergencyContact', models.IntegerField(default=None)),
                ('PermanentAdress', models.CharField(default=None, max_length=200)),
                ('PresentAdress', models.CharField(default=None, max_length=200)),
                ('Mobile', models.IntegerField(default=None)),
                ('EmailId', models.EmailField(default=None, max_length=50)),
                ('PostGraduation', models.FileField(default=None, upload_to='documnets/')),
                ('PostGraduation_university', models.CharField(default=None, max_length=20)),
                ('PostGraduation_Yop', models.DateField(default=None)),
                ('Graduation', models.FileField(default=None, upload_to='documnets/')),
                ('Graduation_university', models.CharField(default=None, max_length=20)),
                ('Graduation_Yop', models.DateField(default=None)),
                ('_12th', models.FileField(default=None, upload_to='documnets/')),
                ('_12th_Board', models.CharField(default=None, max_length=20)),
                ('_12th_Yop', models.DateField(default=None)),
                ('_10th', models.FileField(default=None, upload_to='documnets/')),
                ('_10th_Board', models.CharField(default=None, max_length=20)),
                ('_10th_Yop', models.DateField(default=None)),
                ('Employer1', models.CharField(default=None, max_length=20)),
                ('Designation1', models.CharField(default=None, max_length=25)),
                ('From1', models.DateField(default=None)),
                ('To1', models.DateField(default=None)),
                ('Employer2', models.CharField(default=None, max_length=20)),
                ('Designation2', models.CharField(default=None, max_length=25)),
                ('From2', models.DateField(default=None)),
                ('To2', models.DateField(default=None)),
                ('DOJ', models.DateField(default=None)),
                ('PANNumber', models.CharField(default=None, max_length=10)),
                ('AdharNumber', models.IntegerField(default=None)),
                ('UANNumber', models.IntegerField(default=None)),
                ('BankAccountNumber', models.CharField(default=None, max_length=15)),
                ('IFSCCode', models.CharField(default=None, max_length=10)),
                ('EmployeeSignature', models.FileField(default=None, upload_to='documents/')),
                ('Date', models.DateField(default=None)),
            ],
        ),
    ]
