# Generated by Django 3.0.4 on 2020-03-19 23:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0002_auto_20200317_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedetails',
            old_name='gender',
            new_name='Gender',
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='Mobile',
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='MobileNumber',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='DOJ',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='DateOfBirth',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='EmailId',
            field=models.EmailField(default=None, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='EmployeeSignature',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='From1',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='From2',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='Graduation',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='Graduation_Yop',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='PostGraduation',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='PostGraduation_Yop',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='To1',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='To2',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='_10th',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='_10th_Yop',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='_12th',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='_12th_Yop',
            field=models.DateField(auto_now_add=True),
        ),
    ]
