# Generated by Django 3.0.4 on 2020-03-19 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0003_auto_20200319_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='DOJ',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='DateOfBirth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='From1',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='From2',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='Graduation_Yop',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='PostGraduation_Yop',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='To1',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='To2',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='_10th_Yop',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='_12th_Yop',
            field=models.DateField(),
        ),
    ]
