# Generated by Django 3.0.4 on 2020-03-20 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0004_auto_20200319_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PANCARD', models.FileField(upload_to='documents/')),
                ('ADHARCARD', models.FileField(upload_to='documents/')),
                ('ADDRESS_PROOF', models.FileField(upload_to='documents/')),
                ('PASSPORT_COPY', models.FileField(upload_to='documents/')),
                ('DEGREE_CERTIFICATE', models.FileField(upload_to='documents/')),
                ('SSLC_OR_10TH', models.FileField(upload_to='documents/')),
                ('PUC_OR_12TH', models.FileField(upload_to='documents/')),
                ('PREVIOUS_COMPANY_OFFER_LETTER', models.FileField(upload_to='documents/')),
                ('EXPERIENCE_LETTER', models.FileField(upload_to='documents/')),
                ('RELIEVING_LETTER', models.FileField(upload_to='documents/')),
                ('INCREMENT_LETTER', models.FileField(upload_to='documents/')),
                ('PAYSLIP_MONTH1', models.FileField(upload_to='documents/')),
                ('PAYSLIP_MONTH2', models.FileField(upload_to='documents/')),
                ('PAYSLIP_MONTH3', models.FileField(upload_to='documents/')),
                ('FORM16_or_TAX_COMPUTATION_LETTER_or_FINAL_SETTLEMENT_LETTER', models.FileField(upload_to='documents/')),
                ('PASSPORT_SIZE_PHOTO', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
