# Generated by Django 3.0.4 on 2020-03-20 01:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0005_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachments',
            name='ADDRESS_PROOF',
            field=models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='please choose the valid file')]),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='ADHARCARD',
            field=models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='please choose the valid file')]),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='DEGREE_CERTIFICATE',
            field=models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='please choose the valid file')]),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='EXPERIENCE_LETTER',
            field=models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='please choose the valid file')]),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='FORM16_or_TAX_COMPUTATION_LETTER_or_FINAL_SETTLEMENT_LETTER',
            field=models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='please choose the valid file')]),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='INCREMENT_LETTER',
            field=models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='please choose the valid file')]),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='PANCARD',
            field=models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='please choose the valid file')]),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='PASSPORT_COPY',
            field=models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='please choose the valid file')]),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='PASSPORT_SIZE_PHOTO',
            field=models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='please choose the valid file')]),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='PAYSLIP_MONTH1',
            field=models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='please choose the valid file')]),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='PAYSLIP_MONTH2',
            field=models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='please choose the valid file')]),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='PAYSLIP_MONTH3',
            field=models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='please choose the valid file')]),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='PREVIOUS_COMPANY_OFFER_LETTER',
            field=models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='please choose the valid file')]),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='PUC_OR_12TH',
            field=models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='please choose the valid file')]),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='RELIEVING_LETTER',
            field=models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='please choose the valid file')]),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='SSLC_OR_10TH',
            field=models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='please choose the valid file')]),
        ),
    ]
