# Generated by Django 3.0.4 on 2020-03-20 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0007_auto_20200319_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachments',
            name='EMPLOYEE_NAME',
        ),
    ]
