# Generated by Django 3.0.4 on 2020-03-20 04:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0009_attachments_employee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='AdharNumber',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='MobileNumber',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='[6-9]\\d{9}')]),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='PANNumber',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='UANNumber',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
